# Generated by Django 3.1 on 2020-08-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardCollections',
            new_name='CardCollection',
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='testy.cardcollection')),
            ],
        ),
    ]
